[package]
name = "niboshi-discord"
version = "0.1.0"
authors = ["cancer <zodiac.cancer.j6@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serenity = "0.8.0"
dotenv = "0.15.0"
